model:
  package: gql
  filename: ./gql/models_gen.go # https://github.com/99designs/gqlgen/tree/master/plugin/modelgen
client:
  package: gql
  filename: ./gql/client.go # Where should any generated client go?
models:
  Date:
    model: github.com/99designs/gqlgen/graphql.Time
schema:
  - "./graphql/schema/**/*.graphql" # Where are all the schema files located?
query:
  - "./graphql/query/*.graphql" # Where are all the query files located?
generate:
  clientV2: true
  clientInterfaceName: "ConstellationsGraphqlClient" # Determine the name of the generated client interface
  structFieldsAlwaysPointers: true # Optional: Always use pointers for struct fields (default: true). [same as gqlgen](https://github.com/99designs/gqlgen/blob/e1ef86e795e738654c98553b325a248c02c8c2f8/docs/content/config.md?plain=1#L73)