// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package gql

import (
	"context"
	"net/http"

	"github.com/Yamashou/gqlgenc/clientv2"
)

type ConstellationsGraphqlClient interface {
	Collections(ctx context.Context, offset *int64, limit *int64, interceptors ...clientv2.RequestInterceptor) (*Collections, error)
}

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli *http.Client, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) ConstellationsGraphqlClient {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type Collections_Collections_Collections struct {
	CollectionAddr string "json:\"collectionAddr\" graphql:\"collectionAddr\""
	Name           string "json:\"name\" graphql:\"name\""
	Image          string "json:\"image\" graphql:\"image\""
}

func (t *Collections_Collections_Collections) GetCollectionAddr() string {
	if t == nil {
		t = &Collections_Collections_Collections{}
	}
	return t.CollectionAddr
}
func (t *Collections_Collections_Collections) GetName() string {
	if t == nil {
		t = &Collections_Collections_Collections{}
	}
	return t.Name
}
func (t *Collections_Collections_Collections) GetImage() string {
	if t == nil {
		t = &Collections_Collections_Collections{}
	}
	return t.Image
}

type Collections_Collections struct {
	Collections []*Collections_Collections_Collections "json:\"collections\" graphql:\"collections\""
}

func (t *Collections_Collections) GetCollections() []*Collections_Collections_Collections {
	if t == nil {
		t = &Collections_Collections{}
	}
	return t.Collections
}

type Collections struct {
	Collections Collections_Collections "json:\"collections\" graphql:\"collections\""
}

func (t *Collections) GetCollections() *Collections_Collections {
	if t == nil {
		t = &Collections{}
	}
	return &t.Collections
}

const CollectionsDocument = `query Collections ($offset: Int, $limit: Int) {
	collections(offset: $offset, limit: $limit) {
		collections {
			collectionAddr
			name
			image
		}
	}
}
`

func (c *Client) Collections(ctx context.Context, offset *int64, limit *int64, interceptors ...clientv2.RequestInterceptor) (*Collections, error) {
	vars := map[string]any{
		"offset": offset,
		"limit":  limit,
	}

	var res Collections
	if err := c.Client.Post(ctx, "Collections", CollectionsDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	CollectionsDocument: "Collections",
}
